### ISSUE TITLE
[FEATURE] New buttons for mute/unmute and deafen next to the your avatar icon on Among Us

### ISSUE THREAD

**Issue by MatadorProBr** [OhMyGuus/BetterCrewLink#147]
# Pre-Flight Checklist
Please use this checklist to avoid spamming:

1. [X] I am not asking a question => use the [Discord](https://discord.gg/qDqTzvj4SH) if you are
2. [X] I have checked that someone else has not suggested this using the [search bar](https://github.com/OhMyGuus/BetterCrewLink/issues?q=is%3Aissue)
3. [X] My feature request is not one of the **commonly suggested features**:
- iOS app (its already being development)

**Is your feature request related to a problem? Please describe.**
Sometimes people want to mute the your microphone, but it's kind of difficult since they have to press a button on your keyboard that usually doesn't even remember which one to mute, so until I thought about it and if I could add 2 buttons to mute and to stay deafen? and then I decided to suggest this idea, you can even take the example of this with Discord because it has buttons for you to mute/unmute and stay deafen, like #143 but instead of mute/unmute others, mute/unmute and stay deafen.

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by OhMyGuus** [comment]
Where to place these buttons?  since we don't have a lot of space to work with..

![image](https://user-images.githubusercontent.com/12090928/114566423-89fa0200-9c72-11eb-8397-c8668b14c828.png)
![image](https://user-images.githubusercontent.com/12090928/114566476-9c743b80-9c72-11eb-9e3a-8d16ed4e3744.png)
![image](https://user-images.githubusercontent.com/12090928/114566522-aac25780-9c72-11eb-8198-2b18b659ef17.png)
![image](https://user-images.githubusercontent.com/12090928/114566702-d34a5180-9c72-11eb-82b0-f0e1236b7410.png)
![image](https://user-images.githubusercontent.com/12090928/114566775-e0674080-9c72-11eb-9b32-2d768fb4b2b2.png)

**Comment by OhMyGuus** [comment]
![image](https://user-images.githubusercontent.com/12090928/114569184-0ab9fd80-9c75-11eb-8c41-9babac728379.png)
![image](https://user-images.githubusercontent.com/12090928/114569391-3806ab80-9c75-11eb-9d34-97770b096e81.png)

**Comment by MatadorProBr** [comment]
![image](https://user-images.githubusercontent.com/71022656/114574277-7ee1aa80-9c4f-11eb-856f-f3e586c612d4.png)
![image](https://user-images.githubusercontent.com/71022656/114574282-80ab6e00-9c4f-11eb-9446-4b560d4a9f70.png)
![image](https://user-images.githubusercontent.com/71022656/114574300-843ef500-9c4f-11eb-9287-07693b520798.png)
I think these 3 positions are great

**Comment by OhMyGuus** [comment]
I think I will settle with this one
![image](https://user-images.githubusercontent.com/12090928/114579891-9b490b80-9c7e-11eb-8b02-b22a4e7c3244.png)
