### ISSUE TITLE
[FEATURE] Disable public lobby by default

### ISSUE THREAD

**Issue by RuiNtD** [OhMyGuus/BetterCrewLink#200]
**Is your feature request related to a problem? Please describe.**
Whenever I host a game, it accidentally shows up in the public lobbies.

**Describe the solution you'd like**
Make the public lobby option disabled by default.

**Describe alternatives you've considered**

**Additional context**

**Comment by MatadorProBr** [comment]
???
https://github.com/OhMyGuus/BetterCrewLink/blob/e7344d2a4bfa399c351f688d8c523a443eefd367/src/renderer/settings/Settings.tsx#L416
The option is disabled by default

**Comment by RuiNtD** [comment]
I had a scenario where room host got transferred to me since the host left and the setting got enabled and we started getting random people in our lobby.

**Comment by OhMyGuus** [comment]
There was a bug in 2.6.0 that lobby settings where saved as normal setting as well. This ment that if you joined a public lobby the public lobby setting was enabled as well if you created a new lobby. 


However this is already fixed in 2.6.1 but you probably joined an lobby on 2.6.0 and the setting sticked

**Comment by RuiNtD** [comment]
Nope. This happened on 2.6.1.
EDIT: Possibly related to host being transferred to me?
EDIT 2: I'm not home right now but when I get home I'll try to see if I can replicate it.
